name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2020-q4' # The arm-none-eabi-gcc release to use.
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
           toolchain: nightly
           override: true
           components: rustfmt
           target: armv7r-none-eabihf
    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
         command: build
